import { Dimensions } from 'react-native';

export const BASE_COLOR = '#FF9F1C';
export const BASELIGHT_COLOR = '#FFEBCF';
export const WHITE_COLOR = '#FFFFFF';
export const BLACK_COLOR = '#000000';
export const STRING_COLOR = '#EDEFEF';
export const DARKWHITE_COLOR = '#F7F7F7';
export const SOFTWHITE_COLOR = '#f4f3f3';
export const GRAY_COLOR = '#BBBCBE';
export const SOFTGRAY_COLOR = '#E5E5E5';
export const SOFTGRAY2_COLOR = '#ededed';
export const SOFTGRAY3_COLOR = '#f7f7f7';
export const GRAY2_COLOR = '#d2d2d3';
export const GRAY3_COLOR = '#A5A5A5';
export const GREEN_COLOR = '#00F900';
export const GREENLIGHT_COLOR = '#E3FEF1';
export const WINDOW_WIDTH = Dimensions.get('window').width;
export const WINDOW_HEIGHT = Dimensions.get('window').height;
export const BACKGROUND_COLOR = '#FFFFFF59';
export const RED_COLOR = '#FF0000';
export const BLUE_COLOR = '#0000FF';
export const PINK_COLOR = '#E11584';
